<?php
require_once(APPPATH . 'modules/satuSehatBridge/interface/Terminology/InterfaceTerminologyByStore.php');
require_once(APPPATH . 'modules/satuSehatBridge/repository/Terminology_repository/Store/Ecounter/TerminologyEcounterANC.php');
require_once(APPPATH . 'modules/satuSehatBridge/repository/Terminology_repository/Store/Ecounter/TerminologyEcounterINC.php');
require_once(APPPATH . 'modules/satuSehatBridge/repository/Terminology_repository/Store/Ecounter/TerminologyEcounterKematianIbu.php');
require_once(APPPATH . 'modules/satuSehatBridge/repository/Terminology_repository/Store/Observation/TerminologyUsiaHamil.php');
require_once(APPPATH . 'modules/satuSehatBridge/repository/Terminology_repository/Store/Observation/TerminologyTungkai.php');
require_once(APPPATH . 'modules/satuSehatBridge/repository/Terminology_repository/Store/Observation/TerminologyTrimester.php');
require_once(APPPATH . 'modules/satuSehatBridge/repository/Terminology_repository/Store/Observation/TerminologyTNBB.php');
require_once(APPPATH . 'modules/satuSehatBridge/repository/Terminology_repository/Store/Observation/TerminologyTinggiFundus.php');
require_once(APPPATH . 'modules/satuSehatBridge/repository/Terminology_repository/Store/Observation/TerminologyTinggiBadan.php');
require_once(APPPATH . 'modules/satuSehatBridge/repository/Terminology_repository/Store/Observation/TerminologyTHT.php');
require_once(APPPATH . 'modules/satuSehatBridge/repository/Terminology_repository/Store/Observation/TerminologySuhu.php');
require_once(APPPATH . 'modules/satuSehatBridge/repository/Terminology_repository/Store/Observation/TerminologySklera.php');
require_once(APPPATH . 'modules/satuSehatBridge/repository/Terminology_repository/Store/Observation/TerminologySistolik.php');
require_once(APPPATH . 'modules/satuSehatBridge/repository/Terminology_repository/Store/Observation/TerminologyRhesus.php');
require_once(APPPATH . 'modules/satuSehatBridge/repository/Terminology_repository/Store/Observation/TerminologyPresentasi.php');
require_once(APPPATH . 'modules/satuSehatBridge/repository/Terminology_repository/Store/Observation/TerminologyPerut.php');
require_once(APPPATH . 'modules/satuSehatBridge/repository/Terminology_repository/Store/Observation/TerminologyPernapasan.php');
require_once(APPPATH . 'modules/satuSehatBridge/repository/Terminology_repository/Store/Observation/TerminologyPartus.php');
require_once(APPPATH . 'modules/satuSehatBridge/repository/Terminology_repository/Store/Observation/TerminologyNadi.php');
require_once(APPPATH . 'modules/satuSehatBridge/repository/Terminology_repository/Store/Observation/TerminologyMerokok.php');
require_once(APPPATH . 'modules/satuSehatBridge/repository/Terminology_repository/Store/Observation/TerminologyLila.php');
require_once(APPPATH . 'modules/satuSehatBridge/repository/Terminology_repository/Store/Observation/TerminologyLeher.php');
require_once(APPPATH . 'modules/satuSehatBridge/repository/Terminology_repository/Store/Observation/TerminologyKonjungvita.php');
require_once(APPPATH . 'modules/satuSehatBridge/repository/Terminology_repository/Store/Observation/TerminologyKepalaPAP.php');
require_once(APPPATH . 'modules/satuSehatBridge/repository/Terminology_repository/Store/Observation/TerminologyJumlahJanin.php');
require_once(APPPATH . 'modules/satuSehatBridge/repository/Terminology_repository/Store/Observation/TerminologyJKS.php');
require_once(APPPATH . 'modules/satuSehatBridge/repository/Terminology_repository/Store/Observation/TerminologyIMT.php');
require_once(APPPATH . 'modules/satuSehatBridge/repository/Terminology_repository/Store/Observation/TerminologyHpl.php');
require_once(APPPATH . 'modules/satuSehatBridge/repository/Terminology_repository/Store/Observation/TerminologyHpht.php');
require_once(APPPATH . 'modules/satuSehatBridge/repository/Terminology_repository/Store/Observation/TerminologyGravida.php');
require_once(APPPATH . 'modules/satuSehatBridge/repository/Terminology_repository/Store/Observation/TerminologyGolonganDarah.php');
require_once(APPPATH . 'modules/satuSehatBridge/repository/Terminology_repository/Store/Observation/TerminologyGigidanMulut.php');
require_once(APPPATH . 'modules/satuSehatBridge/repository/Terminology_repository/Store/Observation/TerminologyDiastolik.php');
require_once(APPPATH . 'modules/satuSehatBridge/repository/Terminology_repository/Store/Observation/TerminologyDenyutJanin.php');
require_once(APPPATH . 'modules/satuSehatBridge/repository/Terminology_repository/Store/Observation/TerminologyDada.php');
require_once(APPPATH . 'modules/satuSehatBridge/repository/Terminology_repository/Store/Observation/TerminologyBeratBadan.php');
require_once(APPPATH . 'modules/satuSehatBridge/repository/Terminology_repository/Store/Observation/TerminologyBBSebelumHamil.php');
require_once(APPPATH . 'modules/satuSehatBridge/repository/Terminology_repository/Store/Observation/TerminologyAlkohol.php');
require_once(APPPATH . 'modules/satuSehatBridge/repository/Terminology_repository/Store/Observation/TerminologyAbortus.php');
require_once(APPPATH . 'modules/satuSehatBridge/repository/Terminology_repository/Store/Observation/TaksiranBeratJanin.php');
require_once(APPPATH . 'modules/satuSehatBridge/repository/Terminology_repository/Store/Observation/10T/TerminologyProteinUrin.php');
require_once(APPPATH . 'modules/satuSehatBridge/repository/Terminology_repository/Store/Observation/10T/TerminologyPPIARPR.php');
require_once(APPPATH . 'modules/satuSehatBridge/repository/Terminology_repository/Store/Observation/10T/TerminologyPPIAHIV.php');
require_once(APPPATH . 'modules/satuSehatBridge/repository/Terminology_repository/Store/Observation/10T/TerminologyHepatitisBPPIA.php');
require_once(APPPATH . 'modules/satuSehatBridge/repository/Terminology_repository/Store/Observation/10T/TerminologyHbg.php');
require_once(APPPATH . 'modules/satuSehatBridge/repository/Terminology_repository/Store/Observation/10T/TerminologyGulaDarah.php');
require_once(APPPATH . 'modules/satuSehatBridge/repository/Terminology_repository/Store/Observation/USG/TerminologyUsiaKehamilanUSG.php');
require_once(APPPATH . 'modules/satuSehatBridge/repository/Terminology_repository/Store/Observation/USG/TerminologyLetakJanin.php');
require_once(APPPATH . 'modules/satuSehatBridge/repository/Terminology_repository/Store/Observation/USG/TerminologyHPLUSG.php');
require_once(APPPATH . 'modules/satuSehatBridge/repository/Terminology_repository/Store/Observation/USG/TerminologyHC.php');
require_once(APPPATH . 'modules/satuSehatBridge/repository/Terminology_repository/Store/Observation/USG/TerminologyGS.php');
require_once(APPPATH . 'modules/satuSehatBridge/repository/Terminology_repository/Store/Observation/USG/TerminologyFL.php');
require_once(APPPATH . 'modules/satuSehatBridge/repository/Terminology_repository/Store/Observation/USG/TerminologyDJJ.php');
require_once(APPPATH . 'modules/satuSehatBridge/repository/Terminology_repository/Store/Observation/USG/TerminologyCRL.php');
require_once(APPPATH . 'modules/satuSehatBridge/repository/Terminology_repository/Store/Observation/USG/TerminologyBPD.php');
require_once(APPPATH . 'modules/satuSehatBridge/repository/Terminology_repository/Store/Observation/USG/TerminologyBBJanin.php');
require_once(APPPATH . 'modules/satuSehatBridge/repository/Terminology_repository/Store/Observation/USG/TerminologyAC.php');
require_once(APPPATH . 'modules/satuSehatBridge/repository/Terminology_repository/Store/Condition/TerminologyCondition.php');
require_once(APPPATH . 'modules/satuSehatBridge/repository/Terminology_repository/Store/Ecounter/TerminologyEcounterPNC.php');
require_once(APPPATH . 'modules/satuSehatBridge/repository/Terminology_repository/Store/Condition/TerminologyConditionPNC.php');
class TerminolgyBaseFactoryByStore {

    public function getTerminology ($type): InterfaceTerminologyByStore
    {
        switch ($type) {
            case 'ecounter_inc': return new  TerminologyEcounterINC();
            case 'ecounter_kematian' : return new TerminologyEcounterKematianIbu();
            case 'ecounter_anc': return new TerminologyEcounterANC();
            case 'usia_hamil': return new TerminologyUsiaHamil();
            case 'tungkai': return new TerminologyTungkai();
            case 'trimester': return new TerminologyTrimester();
            case 'tnbb': return new TerminologyTNBB();
            case 'tfu': return new TerminologyTinggiFundus();
            case 'tb': return new TerminologyTinggiBadan();
            case 'tht': return new TerminologyTHT();
            case 'suhu': return new TerminologySuhu();
            case 'sklera': return new TerminologySklera();
            case 'djj_usg':  return new  TerminologyDJJ();
            case 'sistolik': return new TerminologySistolik();
            case 'rhesus': return new TerminologyRhesus();
            case 'presentasi': return new TerminologyPresentasi();
            case 'perut': return new TerminologyPerut();
            case 'napas': return new TerminologyPernapasan();
            case 'partus': return new TerminologyPartus();
            case 'nadi': return new TerminologyNadi();
            case 'rokok': return new TerminologyMerokok();
            case 'lila': return new TerminologyLila();
            case 'leher': return new TerminologyLeher();
            case 'konjungtiva': return new TerminologyKonjungvita();
            case 'kepala_pap': return new TerminologyKepalaPAP();
            case 'jml_janin': return new TerminologyJumlahJanin();
            case 'jks': return new TerminologyJKS();
            case 'imt': return new TerminologyIMT();
            case 'hpl': return new TerminologyHpl();
            case 'hpht': return new TerminologyHpht();
            case 'gravida': return new TerminologyGravida();
            case 'goldar': return new TerminologyGolonganDarah();
            case 'gigi': return new TerminologyGigidanMulut();
            case 'diastolik': return new TerminologyDiastolik();
            case 'djj': return new TerminologyDenyutJanin();
            case 'dada': return new TerminologyDada();
            case 'bb': return new TerminologyBeratBadan();
            case 'bb_sebelum': return new TerminologyBBSebelumHamil();
            case 'alkohol': return new TerminologyAlkohol();
            case 'abortus': return new TerminologyAbortus();
            case 'takberatjanin': return new TaksiranBeratJanin();
            case 'protein_urin': return new TerminologyProteinUrin();
            case 'ppia_rpr': return new TerminologyPPIARPR();
            case 'ppia_hiv': return new TerminologyPPIAHIV();
            case 'ppia_hbsag': return new TerminologyHepatitisBPPIA();
            case 'hbg': return new TerminologyHbg();
            case 'gds': return new TerminologyGulaDarah();
            case 'usia_usg': return new TerminologyUsiaKehamilanUSG();
            case 'letak_janin': return new TerminologyLetakJanin();
            case 'hpl_usg': return new TerminologyHPLUSG();
            case 'hc': return new TerminologyHC();
            case 'gs': return new TerminologyGS();
            case 'fl': return new TerminologyFL();
            case 'crl': return new TerminologyCRL();
            case 'bpd': return new TerminologyBPD();
            case 'bb_janin': return new TerminologyBBJanin();
            case 'ac': return new TerminologyAC();
            case 'condition' : return new TerminologyCondition();
            case 'ecounter_pnc' : return new TerminologyEcounterPNC();
            case 'condition_pnc' : return new TerminologyConditionPNC();

            default:
                throw new Exception("Terminology type '{$type}' tidak dikenali.");
        }
    }
}